[theme]
primaryColor = "#6B8E7F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7F5"
textColor = "#2C3E36"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501
fileWatcherType = "poll"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true
fastReruns = true
