[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true
port = 8503
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

